circle-ci - change config.yml with full workflow and decrease the command in the package.json

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,53 +1,99 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/2.0/configuration-reference
-version: 2.1
-
-# add your orb below, to be used in integration tests (note: a @dev:alpha
-# release must exist.);
-orbs:
-  codecov: codecov/codecov@dev:alpha
-  orb-tools: circleci/orb-tools@10.0
-
-# Pipeline parameters
-parameters:
-  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
-  # job, by default.
-  run-integration-tests:
-    type: boolean
-    default: false
-  dev-orb-version:
-    type: string
-    default: "dev:alpha"
-
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
+version: 2
 jobs:
-  say-hello:
-    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
+  node/test:
     docker:
-      - image: cimg/base:stable
-    # Add steps to the job
-    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
+      - image: cimg/node:13.11.0
     steps:
       - checkout
       - run:
-          name: "Say hello"
-          command: "echo Hello, World!"
-
-  build:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - run:
-          name: CodeCov
           command: |
-            bash <(curl -s https://codecov.io/bash) -Z -t '492fe176-0a7e-4b53-b0fb-d69022f3f1c9' -s coverage
-
-# Invoke jobs via workflows
-# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
+            if [ ! -f "package.json" ]; then
+              echo
+              echo "---"
+              echo "Unable to find your package.json file. Did you forget to set the app-dir parameter?"
+              echo "---"
+              echo
+              echo "Current directory: $(pwd)"
+              echo
+              echo
+              echo "List directory: "
+              echo
+              ls
+              exit 1
+            fi
+          name: Checking for package.json
+          working_directory: ~/project
+      - run:
+          command: |
+            if [ -f "package-lock.json" ]; then
+              echo "Found package-lock.json file, assuming lockfile"
+              ln package-lock.json /tmp/node-project-lockfile
+            elif [ -f "npm-shrinkwrap.json" ]; then
+              echo "Found npm-shrinkwrap.json file, assuming lockfile"
+              ln npm-shrinkwrap.json /tmp/node-project-lockfile
+            elif [ -f "yarn.lock" ]; then
+              echo "Found yarn.lock file, assuming lockfile"
+              ln yarn.lock /tmp/node-project-lockfile
+            fi
+            ln package.json /tmp/node-project-package.json
+          name: Determine lockfile
+          working_directory: ~/project
+      - restore_cache:
+          keys:
+            - node-deps-{{ arch }}-v1-{{ .Branch }}-{{ checksum "/tmp/node-project-package.json" }}-{{ checksum "/tmp/node-project-lockfile" }}
+            - node-deps-{{ arch }}-v1-{{ .Branch }}-{{ checksum "/tmp/node-project-package.json" }}-
+            - node-deps-{{ arch }}-v1-{{ .Branch }}-
+      - run:
+          command: "if [[ ! -z \"\" ]]; then\n  echo \"Running override package installation command:\"\n  \nelse\n  npm ci\nfi\n"
+          name: Installing NPM packages
+          working_directory: ~/project
+      - save_cache:
+          key: node-deps-{{ arch }}-v1-{{ .Branch }}-{{ checksum "/tmp/node-project-package.json" }}-{{ checksum "/tmp/node-project-lockfile" }}
+          paths:
+            - ~/.npm
+      - run:
+          command: npm run coverage
+          name: Run NPM Tests
+          working_directory: ~/project
+      - run:
+          command: |
+            family=$(uname -s | tr '[:upper:]' '[:lower:]')
+            os="windows"
+            [[ $family == "darwin" ]] && os="macos"
+            [[ $family == "linux" ]] && os="linux"
+            echo "Detected ${os}"
+            echo "export os=${os}" >> $BASH_ENV
+            filename="codecov"
+            [[ $os == "windows" ]] && filename+=".exe"
+            echo "export filename=${filename}" >> $BASH_ENV
+            [[ $os == "macos" ]] && brew install gpg
+            curl -Os "https://uploader.codecov.io/latest/${os}/${filename}"
+          name: Download Codecov Uploader
+          when: always
+      - run:
+          command: |
+            curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --import # One-time step
+            curl -Os "https://uploader.codecov.io/latest/${os}/${filename}.SHA256SUM"
+            curl -Os "https://uploader.codecov.io/latest/${os}/${filename}.SHA256SUM.sig"
+            gpg --verify $filename.SHA256SUM.sig $filename.SHA256SUM
+            shasum -a 256 -c $filename.SHA256SUM || sha256sum -c $filename.SHA256SUM
+          name: Validate Codecov Uploader
+      - run:
+          command: |
+            chmod +x $filename
+            args=()
+            [[ -n "" ]] && args+=( "-f " )
+            [[ -n "" ]] && args+=( "" )
+            curl -H "Accept: application/json" "https://uploader.codecov.io/${os}/latest" | grep -o '\"version\":\"v[0-9\.\_]\+\"' | head -1
+            ./$filename \
+              -Q "codecov-circleci-orb-3.1.0" \
+              -t "${CODECOV_TOKEN}" \
+              -n "${CIRCLE_BUILD_NUM}" \
+              -F "" \
+              ${args[@]}
+          name: Upload Coverage Results
 workflows:
-  check-test-coverage-workflow:
+  upload-to-codecov:
     jobs:
-      - build
+      - node/test
+  version: 2
